### ISSUE TITLE
语音命令天猫精灵关灯时出错了

### ISSUE THREAD

**Issue by joelliang** [cnk700i/aihome#7]
home assistant 通过 homekit_controller 插件接上 Aqara 的网关(支持homekit)，控制灯开关。

语音命令天猫精灵去关灯，结果控制不了。
看 log 是 aihome 插件 crash 了。
另外，后面的 log 显示好像 home_controller 更新状态时超时了。

```
2019-06-20 19:38:55 DEBUG (MainThread) [custom_components.aihome] [http] get access_token[eyJ...my_token...RSU]
2019-06-20 19:38:55 DEBUG (MainThread) [custom_components.aihome] [http] validate access_token, get refresh_token(id = d53...my_id_6e3)
2019-06-20 19:38:55 INFO (MainThread) [custom_components.aihome.aligenie] Handle Request: {'header': {'messageId': '39d...my_messageId...50b', 'name': 'Tur
nOff', 'namespace': 'AliGenie.Iot.Device.Control', 'payLoadVersion': 1}, 'payload': {'accessToken': 'eyJ...my_token....RSU', 'attribute': 'powerstate', 'deviceId': 'switch.
wall_switch_5855', 'deviceType': 'light', 'value': 'off'}}
2019-06-20 19:38:55 DEBUG (MainThread) [custom_components.aihome.aligenie] domain: switch, servcie: turn_off, data: {'entity_id': 'switch.wall_switch_5855'}
2019-06-20 19:38:57 ERROR (MainThread) [custom_components.aihome] [http] handle fail: Traceback (most recent call last):
  File "/config/custom_components/aihome/__init__.py", line 526, in post
    response = await HANDLER[platform].handleRequest(json.loads(data), refresh_token)
  File "/config/custom_components/aihome/aligenie.py", line 169, in handleRequest
    result = await self._controlDevice(name, payload)
  File "/config/custom_components/aihome/aligenie.py", line 280, in _controlDevice
    result = await self._hass.services.async_call(domain_list[i], service_list[i], data_list[i], True)
  File "/usr/src/app/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
concurrent.futures._base.CancelledError

2019-06-20 19:38:57 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
2019-06-20 19:39:02 WARNING (MainThread) [homeassistant.components.light] Updating homekit_controller light took longer than the scheduled update interval 0:00:30
```

**Comment by cnk700i** [comment]
每次都是这个报错？

**Comment by cnk700i** [comment]
有问题加qq群反馈吧
